- name: remove existing directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: abesent

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: directory

- name: download app code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ APP_LOCAION }}"
    remote_src: yes